- hosts: localhost
  vars:
    droplet_name: <droplet_and_ts_host_name>
  roles:
    - role: tofu-provisioning
      delegate_to: localhost
    - role: dreamhost-caddy
      delegate_to: "{{ droplet_name }}"